version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: study_index_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: study_index
      MYSQL_USER: study_index_user
      MYSQL_PASSWORD: study_index_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data:
